import Head from "next/head";
import Navbar from "../components/Navbar";
import Map from "../components/Map";

const style = {
  wrapper: `h-screen w-screen flex flex-col`,
};

export default function Home() {
  return (
    <div className={style.wrapper}>
      <Head>
        <title>Uber blockchain clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={style.main}>
        <Map />
      </div>

      <div className={style.rideRequestContainer}>
        <div className={style.rideRequest}>
          {/* location selector */}
          {/* confirm ride */}
        </div>
      </div>
    </div>
  );
}
